project_id = "lipkaxjfwwamwlscgujt"

[functions.close-month]
verify_jwt = false

[functions.create-congregation]
verify_jwt = false

[functions.invite-user]
verify_jwt = false

[functions.delete-profile]
verify_jwt = false

[functions.assign-congregation-admin]
verify_jwt = false

[functions.remove-congregation-admin]
verify_jwt = false

[functions.send-broadcast-notification]
verify_jwt = false

[functions.send-push-notification]
verify_jwt = false

[functions.process-scheduled-notifications]
verify_jwt = false

[functions.transfer-user-congregation]
verify_jwt = false